spring.datasource.driver-class-name: org.apache.derby.jdbc.ClientDriver
spring.datasource.url: jdbc:derby://localhost:1527/EventsToYou
spring.datasource.username: EventsToYou
spring.datasource.password: pass

spring.datasource.tomcat.max-active: 50

spring.jpa.hibernate.ddl-auto: create-drop
spring.jpa.properties.hibernate.dialect: org.hibernate.dialect.DerbyTenSevenDialect